<?
	require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetPageProperty("tags", "hotels in uzbekistan, hotels in tashkent, hotels in samarkand, hotels in bukhara, hotels in khiva, book a hotel in central asia, central asia accomodation, uzbekistan accomodation, 4 star hotels in uzbekistan, 5 star hotels in uzbekistan, cheap hotels in uzbekistan, where to stay in uzbekistan,hotels in kazakhstan, hotels in kyrgyzstan, hotels in turkmenistan, hotels in tajikistan");
$APPLICATION->SetPageProperty("keywords_inner", "hotels in uzbekistan, hotels in tashkent, hotels in samarkand, hotels in bukhara, hotels in khiva, book a hotel in central asia, central asia accomodation, uzbekistan accomodation, 4 star hotels in uzbekistan, 5 star hotels in uzbekistan, cheap hotels in uzbekistan, where to stay in uzbekistan,hotels in kazakhstan, hotels in kyrgyzstan, hotels in turkmenistan, hotels in tajikistan");
$APPLICATION->SetPageProperty("title", "Hotels in Central Asia");
$APPLICATION->SetPageProperty("keywords", "hotels in uzbekistan, hotels in tashkent, hotels in samarkand, hotels in bukhara, hotels in khiva, book a hotel in central asia, central asia accomodation, uzbekistan accomodation, 4 star hotels in uzbekistan, 5 star hotels in uzbekistan, cheap hotels in uzbekistan, where to stay in uzbekistan,hotels in kazakhstan, hotels in kyrgyzstan, hotels in turkmenistan, hotels in tajikistan");
$APPLICATION->SetPageProperty("description", "Book a hotel in Uzbekistan and other Central Asia countries online.");
	$APPLICATION->SetTitle("Hotels in Central Asia");
?><? $APPLICATION->IncludeComponent(
	"bitrix:catalog",
	"hotels",
	array(
		"IBLOCK_TYPE"                      => "hotels",
		"IBLOCK_ID"                        => "19",
		"BASKET_URL"                       => "",
		"ACTION_VARIABLE"                  => "action",
		"PRODUCT_ID_VARIABLE"              => "id",
		"SECTION_ID_VARIABLE"              => "SECTION_ID",
		"SEF_MODE"                         => "Y",
		"SEF_FOLDER"                       => "/hotels/",
		"AJAX_MODE"                        => "N",
		"AJAX_OPTION_SHADOW"               => "Y",
		"AJAX_OPTION_JUMP"                 => "N",
		"AJAX_OPTION_STYLE"                => "Y",
		"AJAX_OPTION_HISTORY"              => "N",
		"CACHE_TYPE"                       => "A",
		"CACHE_TIME"                       => "36000000",
		"CACHE_FILTER"                     => "N",
		"CACHE_GROUPS"                     => "N",
		"SET_TITLE"                        => "Y",
		"SET_STATUS_404"                   => "N",
		"USE_FILTER"                       => "Y",
		"USE_REVIEW"                       => "N",
		"USE_COMPARE"                      => "N",
		"PRICE_CODE"                       => array(),
		"USE_PRICE_COUNT"                  => "N",
		"SHOW_PRICE_COUNT"                 => "1",
		"PRICE_VAT_INCLUDE"                => "Y",
		"PRICE_VAT_SHOW_VALUE"             => "N",
		"SHOW_TOP_ELEMENTS"                => "N",
		"PAGE_ELEMENT_COUNT"               => "12",
		"LINE_ELEMENT_COUNT"               => "3",
		"ELEMENT_SORT_FIELD"               => "sort",
		"ELEMENT_SORT_ORDER"               => "asc",
		"LIST_PROPERTY_CODE"               => array(
			0 => "",
			1 => "REMUNERATION",
			2 => "",
		),
		"INCLUDE_SUBSECTIONS"              => "Y",
		"LIST_META_KEYWORDS"               => "-",
		"LIST_META_DESCRIPTION"            => "-",
		"LIST_BROWSER_TITLE"               => "-",
		"DETAIL_PROPERTY_CODE"             => array(
			0 => "",
			1 => "",
		),
		"DETAIL_META_KEYWORDS"             => "-",
		"DETAIL_META_DESCRIPTION"          => "-",
		"DETAIL_BROWSER_TITLE"             => "-",
		"LINK_IBLOCK_TYPE"                 => "",
		"LINK_IBLOCK_ID"                   => "",
		"LINK_PROPERTY_SID"                => "",
		"LINK_ELEMENTS_URL"                => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"USE_ALSO_BUY"                     => "N",
		"DISPLAY_TOP_PAGER"                => "N",
		"DISPLAY_BOTTOM_PAGER"             => "Y",
		"PAGER_TITLE"                      => "Гостиницы",
		"PAGER_SHOW_ALWAYS"                => "N",
		"PAGER_TEMPLATE"                   => "",
		"PAGER_DESC_NUMBERING"             => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME"  => "36000",
		"PAGER_SHOW_ALL"                   => "N",
		"AJAX_OPTION_ADDITIONAL"           => "",
		"ADD_SECTIONS_CHAIN"               => "Y",
		"ADD_ELEMENT_CHAIN"                => "N",
		"USE_ELEMENT_COUNTER"              => "Y",
		"USE_PRODUCT_QUANTITY"             => "N",
		"ADD_PROPERTIES_TO_BASKET"         => "Y",
		"PRODUCT_PROPS_VARIABLE"           => "prop",
		"PARTIAL_PRODUCT_PROPERTIES"       => "N",
		"PRODUCT_PROPERTIES"               => array(),
		"SECTION_COUNT_ELEMENTS"           => "Y",
		"SECTION_TOP_DEPTH"                => "2",
		"ELEMENT_SORT_FIELD2"              => "id",
		"ELEMENT_SORT_ORDER2"              => "desc",
		"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
		"USE_STORE"                        => "N",
		"PRODUCT_QUANTITY_VARIABLE"        => "quantity",
		"SEF_URL_TEMPLATES"                => array(
			"sections" => "",
			"section"  => "#SECTION_CODE#/",
			"element"  => "element/#ELEMENT_CODE#/",
			"compare"  => "",
		)
	),
	false
); ?>
<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>